# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setObjectName("leftLayout")
        self.video_label = QtWidgets.QLabel(self.centralwidget)
        self.video_label.setMinimumSize(QtCore.QSize(480, 360))
        self.video_label.setStyleSheet("background-color: black; border: 2px solid gray; color: white;")
        self.video_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_label.setObjectName("video_label")
        self.leftLayout.addWidget(self.video_label)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 150))
        self.textBrowser.setObjectName("textBrowser")
        self.leftLayout.addWidget(self.textBrowser)
        self.horizontalLayout.addLayout(self.leftLayout)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setObjectName("rightLayout")
        self.btnRegister = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegister.setObjectName("btnRegister")
        self.rightLayout.addWidget(self.btnRegister)
        self.btnRecognize = QtWidgets.QPushButton(self.centralwidget)
        self.btnRecognize.setObjectName("btnRecognize")
        self.rightLayout.addWidget(self.btnRecognize)
        self.btnShowDB = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowDB.setObjectName("btnShowDB")
        self.rightLayout.addWidget(self.btnShowDB)
        self.btnThresholds = QtWidgets.QPushButton(self.centralwidget)
        self.btnThresholds.setObjectName("btnThresholds")
        self.rightLayout.addWidget(self.btnThresholds)
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setObjectName("btnExit")
        self.rightLayout.addWidget(self.btnExit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.rightLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.rightLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Система распознавания лиц"))
        self.video_label.setText(_translate("MainWindow", "Камера неактивна"))
        self.btnRegister.setText(_translate("MainWindow", "Зарегистрировать пользователя"))
        self.btnRecognize.setText(_translate("MainWindow", "Запуск распознавания"))
        self.btnShowDB.setText(_translate("MainWindow", "Просмотр базы"))
        self.btnThresholds.setText(_translate("MainWindow", "Изменить пороги"))
        self.btnExit.setText(_translate("MainWindow", "Выход"))
