# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import cv2
import numpy as np
from face_recognition import FaceRecognitionSystem
import time
from PyQt5 import QtCore, QtGui, QtWidgets
from video import VideoThread


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setObjectName("leftLayout")
        self.video_label = QtWidgets.QLabel(self.centralwidget)
        self.video_label.setMinimumSize(QtCore.QSize(480, 360))
        self.video_label.setStyleSheet("background-color: black; border: 2px solid gray; color: white;")
        self.video_label.setAlignment(QtCore.Qt.AlignCenter)
        self.video_label.setObjectName("video_label")
        self.leftLayout.addWidget(self.video_label)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 150))
        self.textBrowser.setObjectName("textBrowser")
        self.leftLayout.addWidget(self.textBrowser)
        self.horizontalLayout.addLayout(self.leftLayout)
        self.rightLayout = QtWidgets.QVBoxLayout()
        self.rightLayout.setObjectName("rightLayout")
        self.btnRegister = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegister.setObjectName("btnRegister")
        self.rightLayout.addWidget(self.btnRegister)
        self.btnRecognize = QtWidgets.QPushButton(self.centralwidget)
        self.btnRecognize.setObjectName("btnRecognize")
        self.rightLayout.addWidget(self.btnRecognize)
        self.btnShowDB = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowDB.setObjectName("btnShowDB")
        self.rightLayout.addWidget(self.btnShowDB)
        self.btnThresholds = QtWidgets.QPushButton(self.centralwidget)
        self.btnThresholds.setObjectName("btnThresholds")
        self.rightLayout.addWidget(self.btnThresholds)
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setObjectName("btnExit")
        self.rightLayout.addWidget(self.btnExit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.rightLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.rightLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Система распознавания лиц"))
        self.video_label.setText(_translate("MainWindow", "Камера неактивна"))
        self.btnRegister.setText(_translate("MainWindow", "Зарегистрировать пользователя"))
        self.btnRecognize.setText(_translate("MainWindow", "Запуск распознавания"))
        self.btnShowDB.setText(_translate("MainWindow", "Просмотр базы"))
        self.btnThresholds.setText(_translate("MainWindow", "Изменить пороги"))
        self.btnExit.setText(_translate("MainWindow", "Выход"))


class MainApp(QtWidgets.QMainWindow):
    def __init__(self):
        super(MainApp, self).__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.recognizer = FaceRecognitionSystem()

        # Создаем QLabel для отображения видео, если его нет в UI
        if not hasattr(self.ui, 'video_label'):
            self.video_label = QtWidgets.QLabel(self.ui.centralwidget)
            self.video_label.setGeometry(QtCore.QRect(300, 50, 480, 360))
            self.video_label.setStyleSheet("background-color: black; border: 2px solid gray;")
            self.video_label.setAlignment(QtCore.Qt.AlignCenter)
            self.video_label.setText("Камера неактивна")
            self.video_label.setMinimumSize(480, 360)

        # Поток для видео
        self.video_thread = VideoThread(self.recognizer)
        self.video_thread.change_pixmap_signal.connect(self.update_image)
        self.video_thread.recognition_result.connect(self.on_recognition_result)

        # Подключаем кнопки (без кнопки остановки камеры)
        self.ui.btnRegister.clicked.connect(self.register_user)
        self.ui.btnRecognize.clicked.connect(self.toggle_recognition)
        self.ui.btnShowDB.clicked.connect(self.show_db)
        self.ui.btnThresholds.clicked.connect(self.set_thresholds)
        self.ui.btnExit.clicked.connect(self.close)

        # Лог-виджет
        self.log_widget = self.ui.textBrowser

        # Статус распознавания
        self.recognition_active = False

        # Автоматически запускаем камеру при старте
        self.start_camera()

        self.log("🚀 Система распознавания лиц запущена")
        self.log("👉 Нажмите 'Запуск распознавания' для начала")

    def start_camera(self):
        """Автоматический запуск камеры при старте"""
        if not self.video_thread.isRunning():
            self.video_thread.start()
            self.log("📹 Камера запущена")

    def update_image(self, cv_img):
        """Обновление изображения в QLabel"""
        qt_img = self.convert_cv_qt(cv_img)
        if hasattr(self.ui, 'video_label'):
            self.ui.video_label.setPixmap(qt_img)
        else:
            self.video_label.setPixmap(qt_img)

    def convert_cv_qt(self, cv_img):
        """Конвертация OpenCV image в QPixmap"""
        rgb_image = cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)
        h, w, ch = rgb_image.shape
        bytes_per_line = ch * w
        convert_to_Qt_format = QtGui.QImage(rgb_image.data, w, h, bytes_per_line, QtGui.QImage.Format_RGB888)
        p = convert_to_Qt_format.scaled(480, 360, QtCore.Qt.KeepAspectRatio)
        return QtGui.QPixmap.fromImage(p)

    def on_recognition_result(self, name, confidence):
        """Обработка результата распознавания"""
        if confidence >= self.recognizer.high_thr:
            self.log(f"✅ Распознан: {name} ({confidence:.2f})")
        elif confidence >= self.recognizer.low_thr:
            self.log(f"⚠ Возможно: {name}? ({confidence:.2f})")
        else:
            self.log(f"❌ Неизвестный ({confidence:.2f})")

    def log(self, text):
        """Добавление сообщения в лог"""
        if self.log_widget:
            self.log_widget.append(text)
            scrollbar = self.log_widget.verticalScrollBar()
            scrollbar.setValue(scrollbar.maximum())
        print(f"[LOG] {text}")

    def register_user(self):
        """Регистрация нового пользователя"""
        if self.recognition_active:
            self.log("❌ Сначала остановите распознавание!")
            return

        name, ok = QtWidgets.QInputDialog.getText(self, "Регистрация", "Введите имя:")
        if ok and name:
            if name in self.recognizer.db.all_faces():
                self.log(f"⚠ Пользователь {name} уже существует!")
                return

            self.log(f"🔍 Регистрация {name}... Смотрите в камеру!")

            # Ждем обнаружения лица
            face_detected = False
            for attempt in range(50):
                # В реальном приложении здесь должен быть код для захвата кадра и детекции лица
                time.sleep(0.1)

                # Для демонстрации имитируем обнаружение лица
                if attempt == 25:
                    face_detected = True
                    break

            if face_detected:
                # Создаем фиктивные features (в реальном приложении извлекаем из лица)
                dummy_features = np.random.rand(512).astype(np.float32)
                self.recognizer.db.add_face(name, dummy_features)
                self.log(f"🎉 Пользователь {name} успешно зарегистрирован!")
            else:
                self.log("❌ Не удалось обнаружить лицо для регистрации")

    def toggle_recognition(self):
        """Включение/выключение распознавания"""
        if not self.recognizer.db.has_faces():
            self.log("❌ База пуста! Сначала зарегистрируйте пользователей.")
            return

        if not self.recognition_active:
            # Запускаем распознавание
            self.video_thread.recognition_enabled = True
            self.recognition_active = True
            self.ui.btnRecognize.setText("Остановить распознавание")
            self.ui.btnRecognize.setStyleSheet("background-color: orange;")
            self.log("🔍 Распознавание запущено...")
        else:
            # Останавливаем распознавание
            self.video_thread.recognition_enabled = False
            self.recognition_active = False
            self.ui.btnRecognize.setText("Запуск распознавания")
            self.ui.btnRecognize.setStyleSheet("")
            self.log("🛑 Распознавание остановлено")

    def show_db(self):
        """Показать список зарегистрированных пользователей"""
        faces = self.recognizer.db.all_faces()
        if faces:
            user_list = "\n".join([f"• {name}" for name in faces.keys()])
            self.log(f"👥 Зарегистрированные пользователи ({len(faces)}):\n{user_list}")
        else:
            self.log("❌ База данных пуста")

    def set_thresholds(self):
        """Установка порогов распознавания"""
        current_low = self.recognizer.low_thr
        current_high = self.recognizer.high_thr

        low, ok1 = QtWidgets.QInputDialog.getDouble(
            self, "Нижний порог",
            "Порог для 'сомнительного' распознавания:",
            current_low, 0.1, 0.9, 2
        )
        if not ok1:
            return

        high, ok2 = QtWidgets.QInputDialog.getDouble(
            self, "Верхний порог",
            "Порог для 'уверенного' распознавания:",
            current_high, low, 1.0, 2
        )
        if not ok2:
            return

        self.recognizer.low_thr = low
        self.recognizer.high_thr = high
        self.log(f"✅ Пороги обновлены:")
        self.log(f"   • Сомнительное распознавание: ≥ {low:.2f}")
        self.log(f"   • Уверенное распознавание: ≥ {high:.2f}")

    def closeEvent(self, event):
        """Обработчик закрытия окна"""
        self.video_thread.stop()
        if self.video_thread.isRunning():
            self.video_thread.wait(2000)  # Ждем до 2 секунд
        event.accept()
